# Site settings
title: dannyZhou 的博客
email: zhoujian8585169@126.com
description: > # this means to ignore newlines until "baseurl:"
    这里是 dannyZhou 的博客
baseurl: "/blogs/" # the subpath of your site, e.g. /blog/
url: "http://dannyzhou.github.io/blogs" # the base hostname & protocol for your site
twitter_username: dannyZhou
github_username: dannyZhou 

permalink: /:year/:month/:day/:title/

# Build settings
markdown: kramdown
